//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	kedav1alpha1 "github.com/kedacore/keda/v2/apis/keda/v1alpha1"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSDynamoDB) DeepCopyInto(out *AWSDynamoDB) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(string)
		**out = **in
	}
	if in.QueryKeyJSONPath != nil {
		in, out := &in.QueryKeyJSONPath, &out.QueryKeyJSONPath
		*out = new(string)
		**out = **in
	}
	if in.DataJSONPath != nil {
		in, out := &in.DataJSONPath, &out.DataJSONPath
		*out = new(string)
		**out = **in
	}
	if in.RetrieveQuery != nil {
		in, out := &in.RetrieveQuery, &out.RetrieveQuery
		*out = new(string)
		**out = **in
	}
	if in.ClearQuery != nil {
		in, out := &in.ClearQuery, &out.ClearQuery
		*out = new(string)
		**out = **in
	}
	if in.FailQuery != nil {
		in, out := &in.FailQuery, &out.FailQuery
		*out = new(string)
		**out = **in
	}
	if in.AccessKeySecretName != nil {
		in, out := &in.AccessKeySecretName, &out.AccessKeySecretName
		*out = new(string)
		**out = **in
	}
	if in.IdentityOwner != nil {
		in, out := &in.IdentityOwner, &out.IdentityOwner
		*out = new(string)
		**out = **in
	}
	if in.PodIdentityProvider != nil {
		in, out := &in.PodIdentityProvider, &out.PodIdentityProvider
		*out = new(string)
		**out = **in
	}
	if in.ScaleTargetValue != nil {
		in, out := &in.ScaleTargetValue, &out.ScaleTargetValue
		*out = new(string)
		**out = **in
	}
	if in.ScaleExpressionAttributeNames != nil {
		in, out := &in.ScaleExpressionAttributeNames, &out.ScaleExpressionAttributeNames
		*out = new(string)
		**out = **in
	}
	if in.ScaleKeyConditionExpression != nil {
		in, out := &in.ScaleKeyConditionExpression, &out.ScaleKeyConditionExpression
		*out = new(string)
		**out = **in
	}
	if in.ScaleExpressionAttributeValues != nil {
		in, out := &in.ScaleExpressionAttributeValues, &out.ScaleExpressionAttributeValues
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSDynamoDB.
func (in *AWSDynamoDB) DeepCopy() *AWSDynamoDB {
	if in == nil {
		return nil
	}
	out := new(AWSDynamoDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSQS) DeepCopyInto(out *AWSSQS) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.QueueURL != nil {
		in, out := &in.QueueURL, &out.QueueURL
		*out = new(string)
		**out = **in
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.AccessKeySecretName != nil {
		in, out := &in.AccessKeySecretName, &out.AccessKeySecretName
		*out = new(string)
		**out = **in
	}
	if in.QueueLength != nil {
		in, out := &in.QueueLength, &out.QueueLength
		*out = new(string)
		**out = **in
	}
	if in.IdentityOwner != nil {
		in, out := &in.IdentityOwner, &out.IdentityOwner
		*out = new(string)
		**out = **in
	}
	if in.PodIdentityProvider != nil {
		in, out := &in.PodIdentityProvider, &out.PodIdentityProvider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSQS.
func (in *AWSSQS) DeepCopy() *AWSSQS {
	if in == nil {
		return nil
	}
	out := new(AWSSQS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cassandra) DeepCopyInto(out *Cassandra) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.QueryReturnsKey != nil {
		in, out := &in.QueryReturnsKey, &out.QueryReturnsKey
		*out = new(bool)
		**out = **in
	}
	if in.RetrieveQuery != nil {
		in, out := &in.RetrieveQuery, &out.RetrieveQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureQuery != nil {
		in, out := &in.FailureQuery, &out.FailureQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.ClearQuery != nil {
		in, out := &in.ClearQuery, &out.ClearQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleQuery != nil {
		in, out := &in.ScaleQuery, &out.ScaleQuery
		*out = new(string)
		**out = **in
	}
	if in.TargetQueryValue != nil {
		in, out := &in.TargetQueryValue, &out.TargetQueryValue
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cassandra.
func (in *Cassandra) DeepCopy() *Cassandra {
	if in == nil {
		return nil
	}
	out := new(Cassandra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployStatus) DeepCopyInto(out *DeployStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployStatus.
func (in *DeployStatus) DeepCopy() *DeployStatus {
	if in == nil {
		return nil
	}
	out := new(DeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPubSub) DeepCopyInto(out *GCPPubSub) {
	*out = *in
	if in.CredentialsSecretName != nil {
		in, out := &in.CredentialsSecretName, &out.CredentialsSecretName
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.PodIdentityProvider != nil {
		in, out := &in.PodIdentityProvider, &out.PodIdentityProvider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPubSub.
func (in *GCPPubSub) DeepCopy() *GCPPubSub {
	if in == nil {
		return nil
	}
	out := new(GCPPubSub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDB) DeepCopyInto(out *MongoDB) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.ScaleQuery != nil {
		in, out := &in.ScaleQuery, &out.ScaleQuery
		*out = new(string)
		**out = **in
	}
	if in.QueryValue != nil {
		in, out := &in.QueryValue, &out.QueryValue
		*out = new(string)
		**out = **in
	}
	if in.RetrieveQuery != nil {
		in, out := &in.RetrieveQuery, &out.RetrieveQuery
		*out = new(string)
		**out = **in
	}
	if in.FailureQuery != nil {
		in, out := &in.FailureQuery, &out.FailureQuery
		*out = new(string)
		**out = **in
	}
	if in.ClearQuery != nil {
		in, out := &in.ClearQuery, &out.ClearQuery
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDB.
func (in *MongoDB) DeepCopy() *MongoDB {
	if in == nil {
		return nil
	}
	out := new(MongoDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL) DeepCopyInto(out *MySQL) {
	*out = *in
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.QueryReturnsKey != nil {
		in, out := &in.QueryReturnsKey, &out.QueryReturnsKey
		*out = new(bool)
		**out = **in
	}
	if in.RetrieveQuery != nil {
		in, out := &in.RetrieveQuery, &out.RetrieveQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureQuery != nil {
		in, out := &in.FailureQuery, &out.FailureQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.ClearQuery != nil {
		in, out := &in.ClearQuery, &out.ClearQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.TargetQueryValue != nil {
		in, out := &in.TargetQueryValue, &out.TargetQueryValue
		*out = new(int)
		**out = **in
	}
	if in.ScaleQuery != nil {
		in, out := &in.ScaleQuery, &out.ScaleQuery
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL.
func (in *MySQL) DeepCopy() *MySQL {
	if in == nil {
		return nil
	}
	out := new(MySQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Postgres) DeepCopyInto(out *Postgres) {
	*out = *in
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.QueryReturnsKey != nil {
		in, out := &in.QueryReturnsKey, &out.QueryReturnsKey
		*out = new(bool)
		**out = **in
	}
	if in.RetrieveQuery != nil {
		in, out := &in.RetrieveQuery, &out.RetrieveQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureQuery != nil {
		in, out := &in.FailureQuery, &out.FailureQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.ClearQuery != nil {
		in, out := &in.ClearQuery, &out.ClearQuery
		*out = new(SqlQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.TargetQueryValue != nil {
		in, out := &in.TargetQueryValue, &out.TargetQueryValue
		*out = new(int)
		**out = **in
	}
	if in.ScaleQuery != nil {
		in, out := &in.ScaleQuery, &out.ScaleQuery
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Postgres.
func (in *Postgres) DeepCopy() *Postgres {
	if in == nil {
		return nil
	}
	out := new(Postgres)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcX) DeepCopyInto(out *ProcX) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcX.
func (in *ProcX) DeepCopy() *ProcX {
	if in == nil {
		return nil
	}
	out := new(ProcX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcX) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcXList) DeepCopyInto(out *ProcXList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProcX, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcXList.
func (in *ProcXList) DeepCopy() *ProcXList {
	if in == nil {
		return nil
	}
	out := new(ProcXList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcXList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcXSpec) DeepCopyInto(out *ProcXSpec) {
	*out = *in
	if in.ScalerType != nil {
		in, out := &in.ScalerType, &out.ScalerType
		*out = new(ScalerType)
		**out = **in
	}
	if in.AWSDynamoDB != nil {
		in, out := &in.AWSDynamoDB, &out.AWSDynamoDB
		*out = new(AWSDynamoDB)
		(*in).DeepCopyInto(*out)
	}
	if in.AWSSQS != nil {
		in, out := &in.AWSSQS, &out.AWSSQS
		*out = new(AWSSQS)
		(*in).DeepCopyInto(*out)
	}
	if in.Cassandra != nil {
		in, out := &in.Cassandra, &out.Cassandra
		*out = new(Cassandra)
		(*in).DeepCopyInto(*out)
	}
	if in.GCPPubSub != nil {
		in, out := &in.GCPPubSub, &out.GCPPubSub
		*out = new(GCPPubSub)
		(*in).DeepCopyInto(*out)
	}
	if in.MongoDB != nil {
		in, out := &in.MongoDB, &out.MongoDB
		*out = new(MongoDB)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQL)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(Postgres)
		(*in).DeepCopyInto(*out)
	}
	if in.RabbitMQ != nil {
		in, out := &in.RabbitMQ, &out.RabbitMQ
		*out = new(RabbitMQ)
		(*in).DeepCopyInto(*out)
	}
	if in.RedisList != nil {
		in, out := &in.RedisList, &out.RedisList
		*out = new(RedisList)
		(*in).DeepCopyInto(*out)
	}
	if in.HostEnv != nil {
		in, out := &in.HostEnv, &out.HostEnv
		*out = new(bool)
		**out = **in
	}
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(bool)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicaCount != nil {
		in, out := &in.MinReplicaCount, &out.MinReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicaCount != nil {
		in, out := &in.MaxReplicaCount, &out.MaxReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.CoolDownPeriod != nil {
		in, out := &in.CoolDownPeriod, &out.CoolDownPeriod
		*out = new(int32)
		**out = **in
	}
	if in.PollingInterval != nil {
		in, out := &in.PollingInterval, &out.PollingInterval
		*out = new(int32)
		**out = **in
	}
	if in.ServiceAccountName != nil {
		in, out := &in.ServiceAccountName, &out.ServiceAccountName
		*out = new(string)
		**out = **in
	}
	if in.CommonLabels != nil {
		in, out := &in.CommonLabels, &out.CommonLabels
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = new([]v1.LocalObjectReference)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.LocalObjectReference, len(*in))
			copy(*out, *in)
		}
	}
	if in.EnvSecretNames != nil {
		in, out := &in.EnvSecretNames, &out.EnvSecretNames
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = new([]v1.VolumeMount)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.VolumeMount, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = new([]v1.Volume)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.Volume, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcXSpec.
func (in *ProcXSpec) DeepCopy() *ProcXSpec {
	if in == nil {
		return nil
	}
	out := new(ProcXSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcXStatus) DeepCopyInto(out *ProcXStatus) {
	*out = *in
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeployStatus != nil {
		in, out := &in.DeployStatus, &out.DeployStatus
		*out = new(DeployStatus)
		**out = **in
	}
	if in.ScaledObjectStatus != nil {
		in, out := &in.ScaledObjectStatus, &out.ScaledObjectStatus
		*out = new(ScaledObjectStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcXStatus.
func (in *ProcXStatus) DeepCopy() *ProcXStatus {
	if in == nil {
		return nil
	}
	out := new(ProcXStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQ) DeepCopyInto(out *RabbitMQ) {
	*out = *in
	if in.URLSecretName != nil {
		in, out := &in.URLSecretName, &out.URLSecretName
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQ.
func (in *RabbitMQ) DeepCopy() *RabbitMQ {
	if in == nil {
		return nil
	}
	out := new(RabbitMQ)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisList) DeepCopyInto(out *RedisList) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.ListLength != nil {
		in, out := &in.ListLength, &out.ListLength
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisList.
func (in *RedisList) DeepCopy() *RedisList {
	if in == nil {
		return nil
	}
	out := new(RedisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaledObjectStatus) DeepCopyInto(out *ScaledObjectStatus) {
	*out = *in
	if in.LastActiveTime != nil {
		in, out := &in.LastActiveTime, &out.LastActiveTime
		*out = (*in).DeepCopy()
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(map[string]kedav1alpha1.HealthStatus)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]kedav1alpha1.HealthStatus, len(*in))
			for key, val := range *in {
				(*out)[key] = *val.DeepCopy()
			}
		}
	}
	if in.PausedReplicaCount != nil {
		in, out := &in.PausedReplicaCount, &out.PausedReplicaCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaledObjectStatus.
func (in *ScaledObjectStatus) DeepCopy() *ScaledObjectStatus {
	if in == nil {
		return nil
	}
	out := new(ScaledObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlQuery) DeepCopyInto(out *SqlQuery) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlQuery.
func (in *SqlQuery) DeepCopy() *SqlQuery {
	if in == nil {
		return nil
	}
	out := new(SqlQuery)
	in.DeepCopyInto(out)
	return out
}
